### ISSUE TITLE
关于读取本地视频来做测试的帧率低的问题

### ISSUE THREAD

**Issue by ferch** [weilly0912/Python-TensorflowLite-DEMO#3]
您好，我在I.MX8MP上试用了您的[YOLOv5s_DrownsyDectetion_v2](https://github.com/weilly0912/ATU_NXP_AI_DEMO/tree/v12.0/TensorflowLite_DEMO/YOLOv5s_DrownsyDectetion_v2)这个案例，用摄像头的效果还不错。但是直接换成本地MP4流的时候就帧率低了。我本地视频是720p的。
~~~
V4L2_YUV2_720p = "./img/720p.mp4"
~~~
直接这样用，是可以解析出来但是帧率很低。
换成用GST来解析（这个gst流是测试过的，可以50fps播放。）
~~~
V4L2_YUV2_720p =  '''filesrc location=./img/720p.mp4 ! 
				   qtdemux ! h264parse ! v4l2h264dec ! tee name=t t. ! queue ! videorate ! imxvideoconvert_g2d ! 
				   video/x-raw,format=BGRx ! appsink'''
~~~

就会报错，参数不对。报错如下
~~~
[ WARN:0@20.477] global cap_gstreamer.cpp:1728 open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
Open Camera Success !!
Input data shape: (1, 256, 4, 256)
Traceback (most recent call last):
  File "/home/root/ml/YOLOv5s_DrownsyDectetion_v2/app.py", line 410, in <module>
    main()
  File "/home/root/ml/YOLOv5s_DrownsyDectetion_v2/app.py", line 341, in main
    interpreter.set_tensor(input_details[0]['index'], input_data ) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tflite_runtime/interpreter.py", line 697, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
ValueError: Cannot set tensor: Dimension mismatch. Got 4 but expected 256 for dimension 1 of input 0.
~~~
想请教下怎么解决这个问题

**Comment by weilly0912** [comment]
建議先測試 GStreamer 的指令，然後再整理至 python app 中。 
如果是 i.MX8MP 可試看看以下指令! 
gst-launch-1.0 filesrc location=test_1920x1080.mp4 ! qtdemux name=d d.video_0 ! queue ! h264parse ! vpudec ! queue ! fpsdisplaysink
謝謝

**Comment by weilly0912** [comment]
> site-packages/tflite_runtime/interpreter.py", line 697, in set_tensor

若針對這問題，應該是檢查格式 ( 1,3,x,x)

**Comment by ferch** [comment]
谢谢您，我再检查看看 大概率是因为 format=BGRx  这个格式导致的输入参数变成了四个，而模型需要接入的参数是三个。

另外您这边建议使用的的读取`本地视频`和`camera`的gststream  pipline是怎么样的呢。可否请教下
例如这个
`V4L2_YUV2_720p =  '''filesrc location=./img/720p.mp4 ! 
				   qtdemux ! h264parse ! v4l2h264dec ! tee name=t t. ! queue ! videorate ! imxvideoconvert_g2d ! 
				   video/x-raw,format=BGRx ! appsink'''`

**Comment by weilly0912** [comment]
@ferch Sorry, 這裡我比較不會關注. 若有新的問題不妨寄信到 weilly.li@wpi-group.com ! 謝謝
